### PR TITLE
2017 S1.cpp solution

### PR DESCRIPTION
**Pull request by alexapostolu**
Here's the solution for 2017 s1.cpp. I checked it and it got full marks in the grader

### CODE REVIEW

**Comment by sjay05** [comment]
Hi. Thanks for the pull request, I'll be sure to merge it. Would you be able add like a small explanation of what your idea towards the problem is as a comment on the code?

**Comment by alexapostolu** [comment]
Oh yeah sure, of course. Like a line by line explanation? Or more just what I was doing in general?

**Comment by sjay05** [comment]
More of like a shorter version of the comments you see at http://mmhs.ca/ccc/2015/2015j5.txt.

**Comment by alexapostolu** [comment]
Oh okay sure

**Comment by alexapostolu** [comment]
Sorry if the description is bad, I'm not really good at explaining my code

**Pull request merged**
