### PR TITLE
Added some solutions

### PR DESCRIPTION
**Pull request by alexapostolu**
Added some solutions. All of them got full marks on the CCC grader

### CODE REVIEW

**Comment by sjay05** [comment]
As for CCC 2020 S3, even if it passes on the official grader I'd rather have the polynomial hashing solution as it refers as a better benchmark for hash-breaker cases that `std::hash` fails for if tested with. 

Furthermore your code `TLE`'s on DMOJ. Not sure if this is because of `std::hash` or complexity.

I will check the rest of the files after.

**Comment by alexapostolu** [comment]
Oh, I never noticed that. I'll try them again on DMOJ

Update: I tried the other 4 files and they got full marks on DMOJ as well, however they have minor warnings, mostly for comparing unsigned types to signed typed. I can fix them if you'd like?

**Comment by sjay05** [comment]
If you could that'll be great. So with the fix of the errors, the 4 files apart from the CCC 2020 S3 are ready for merge.

**Comment by alexapostolu** [comment]
Should be good to go now

**Comment by sjay05** [comment]
Under files changed it still seems that the pull request has changes for ccc20s3. Would you be able to change it so that only the other 4 files are part of the merge? 

Or is it something on my side? I'm not sure exactly how to exclude a file in a merge...

**Comment by alexapostolu** [comment]
I just deleted that file, I think it should work now

**Comment by sjay05** [comment]
Merged. If you don't mind is it ok if I modify some of the indenting to match with the repo's c++ style?

**Comment by alexapostolu** [comment]
Sure, np

**Comment by alexapostolu** [comment]
Just for future reference, how would you prefer the indentation?

**Comment by sjay05** [comment]
Nothing much. For brackets I'd rather have them like this...

```
for (int i = 0; i < n; i++) {
 ... code
}
```

and 2-space indenting. 

Thanks!

**Pull request merged**
