### PR TITLE
Created 2018 S2.cpp

### PR DESCRIPTION
**Pull request by alexapostolu**
Solution for 2018 S2 Sunflowers problem in C++. I tested it on the CCC grader and got full marks

### CODE REVIEW

**Comment by sjay05** [comment]
Since the problem is also the `J4` for 2018 could you rename the file to `J4/S2.cpp`.

**Comment by sjay05** [comment]
And also could you add your username as the author as I have in other `.cpp` files.

**Comment by alexapostolu** [comment]
Oh yeah sure, but whenever I try to write `J4/S2.cpp`, it creates a new folder...

**Comment by sjay05** [comment]
Ok `J4S2.cpp` is fine as well, thanks.

**Pull request merged**
